### ISSUE TITLE
Parsing html with an invalid url will crash Parse

### ISSUE THREAD

**Issue by pstuifzand** [willnorris/microformats#8]
The microformats parser will crash when url.Parse returns an error. The "parsed" will be nil and this will crash inside ResolveReference.

I found it while parsing: <https://chat.indieweb.org/dev/2018-04-17>. This will also crash when run with `gomf https://chat.indieweb.org/dev/2018-04-17`

https://github.com/willnorris/microformats/blob/bc552049783fddac99a36ffb65bf3c99f12b64d7/microformats.go#L226

(Originally published at: https://publog.stuifzandapp.com/posts/567)

**Comment by willnorris** [comment]
For a test case, the URL that is failing is "http://vrij-inter.net profile bijnasimon"
